name       : font-manager
version    : 0.8.6
release    : 13
source     :
    - https://github.com/FontManager/font-manager/releases/download/0.8.6/font-manager-0.8.6.tar.xz : e690b8de44ac863a3d4ce3857fe40c035151c6f54b8ff9ec4ff2a3593eed0cf6
homepage   : http://fontmanager.github.io/
license    : GPL-3.0-or-later
component  : office
summary    : A simple font management application
description: |
    A simple font management application for GTK Desktop Environments.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(nautilus-python)
    - pkgconfig(webkit2gtk-4.0)
    - file-roller
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - file-roller
setup      : |
    %meson_configure -Dnautilus=true
build      : |
    %ninja_build
install    : |
    %ninja_install
