name       : font-manager
version    : 0.7.3
release    : 3
source     :
    - https://github.com/FontManager/master/releases/download/0.7.3/font-manager-0.7.3.tar.bz2 : c1114b5ac6fbca16dd478e246e0378b3d43465b5f159001d5fa55b52104be6ca
license    : GPL-3.0
component  : office
summary    : A simple font management application.
description: |
    A simple font management application.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gee-0.8)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(nautilus-python)
    - pkgconfig(pangocairo)
    - pkgconfig(sqlite3)
    - file-roller
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - file-roller
setup      : |
    %configure --with-nautilus
build      : |
    %make -j1
install    : |
    %make_install
    ls
