name       : font-manager
version    : 0.7.5
release    : 8
source     :
    - https://github.com/FontManager/font-manager/archive/0.7.5.tar.gz : a5912b705f379f57025f6c2524d591baebe841b188fd56ceabdebd3756989017
license    : GPL-3.0-or-later
component  : office
summary    : A simple font management application.
description: |
    A simple font management application.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(nautilus-python)
    - pkgconfig(sqlite3)
    - file-roller
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - file-roller
setup      : |
    %patch -p1 < $pkgfiles/Fix-build-failure-with-new-Vala-versions.patch
    %patch -p1 < $pkgfiles/Fix-segfault-due-to-difference-in-code-generated.patch
    %meson_configure -Dnautilus=true
build      : |
    %ninja_build
install    : |
    %ninja_install
