name       : font-manager
version    : 0.8.7
release    : 15
source     :
    - https://github.com/FontManager/font-manager/releases/download/0.8.7/font-manager-0.8.7.tar.xz : 0375119e332e807c71b1da94fbab2d5d3433e62fa308181afa8558e796ce6cda
homepage   : https://fontmanager.github.io/
license    : GPL-3.0-or-later
component  : office
summary    : A simple font management application
description: |
    A simple font management application for GTK Desktop Environments.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(nautilus-python)
    - pkgconfig(webkit2gtk-4.0)
    - file-roller
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - file-roller
setup      : |
    %patch -p1 < $pkgfiles/Add-skip-annotation-to-fsType_to_string.patch
    %meson_configure -Dnautilus=true
build      : |
    %ninja_build
install    : |
    %ninja_install
