name       : font-manager
version    : 0.7.7
release    : 10
source     :
    - https://github.com/FontManager/font-manager/archive/0.7.7.tar.gz : e8a2930a46735b1a5357dc5f7bd8ed2aa05546229fd98f7c055933896a993f2e
homepage   : http://fontmanager.github.io/
license    : GPL-3.0-or-later
component  : office
summary    : A simple font management application.
description: |
    A simple font management application for GTK Desktop Environments.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(nautilus-python)
    - pkgconfig(sqlite3)
    - file-roller
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - file-roller
setup      : |
    %meson_configure -Dnautilus=true
build      : |
    %ninja_build
install    : |
    %ninja_install
