name       : font-manager
version    : 0.8.8
release    : 16
source     :
    - https://github.com/FontManager/font-manager/releases/download/0.8.8/font-manager-0.8.8.tar.xz : b6b6e7c62ce7a407f4151beb890b4dabfb1b2e446ff51f087f1b4fab986f8e79
homepage   : https://fontmanager.github.io/
license    : GPL-3.0-or-later
component  : office
summary    : A simple font management application
description: |
    A simple font management application for GTK Desktop Environments.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(nautilus-python)
    - pkgconfig(webkit2gtk-4.0)
    - file-roller
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - file-roller
setup      : |
    %meson_configure -Dnautilus=true
build      : |
    %ninja_build
install    : |
    %ninja_install
